# Generated by Django 4.2.28 on 2026-10-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aiconfiguration_tts'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconfiguration',
            name='cartesia_api_key',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='aiconfiguration',
            name='tts_provider',
            field=models.CharField(choices=[('gemini', 'Google Gemini'), ('cartesia', 'Cartesia')], default='gemini', max_length=30),
        ),
        migrations.AlterField(
            model_name='aiconfiguration',
            name='provider',
            field=models.CharField(choices=[('gemini', 'Google Gemini'), ('cartesia', 'Cartesia')], default='gemini', max_length=30),
        ),
    ]
